#!/bin/bash
# SPDX-FileCopyrightText: 2026 WebSpider Studios
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# WebSpider 3D Build Script
# Builds Blender (always Release) + WebSpider 3D (environment from settings.sh)

# Load all settings from settings.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/settings.sh"

# Use WEBSPIDER_ENV directly from settings.sh (already exported there)
# Blender always builds in Release mode for optimal performance
BLENDER_BUILD_ENV="Release"

# Define build directory for this environment
BUILD_ENV_DIR="${BUILD_DIR}/${WEBSPIDER_ENV}"

# Overlay WebSpider 3D sources onto source
echo "Overlaying WebSpider 3D sources onto source..."
"$SCRIPT_DIR/overlay.sh"

# Configure build directory
mkdir -p "${BUILD_ENV_DIR}"

# Generate environment configuration header
echo "Generating environment configuration for: $WEBSPIDER_ENV"
mkdir -p "$SOURCE_DIR/source/creator"
cat > "$SOURCE_DIR/source/creator/webspider_env_config.h" << EOF
#pragma once
// Auto-generated file - DO NOT EDIT
// Generated for environment: $WEBSPIDER_ENV

#define WEBSPIDER_BASE_URL "$WEBSPIDER_BACKEND_URL"
#define WEBSPIDER_FRONTEND_BASE_URL "$WEBSPIDER_FRONTEND_URL"
#define WEBSPIDER_CURRENT_ENV "$WEBSPIDER_ENV"

// Environment-specific macros for conditional compilation
EOF

# Generate environment-specific macro based on current WEBSPIDER_ENV
case "$WEBSPIDER_ENV" in
    "Prod")
        echo "#define WEBSPIDER_ENV_PROD" >> "$SOURCE_DIR/source/creator/webspider_env_config.h"
        ;;
    "Dev")
        echo "#define WEBSPIDER_ENV_DEV" >> "$SOURCE_DIR/source/creator/webspider_env_config.h"
        ;;
    "UAT"|"Uat")
        echo "#define WEBSPIDER_ENV_UAT" >> "$SOURCE_DIR/source/creator/webspider_env_config.h"
        ;;
    *)
        echo "#define WEBSPIDER_ENV_PROD  // Default to production for unknown environment" >> "$SOURCE_DIR/source/creator/webspider_env_config.h"
        ;;
esac

# Emit the build-frozen Python env marker (mirrors webspider_env_config.h on the
# Python side). Used by webspider.config.config.get_dev_bypass_credentials() to
# gate the dev bypass behind a value that cannot be flipped by editing the
# bundled webspider.json. Only Dev builds get DEV_BYPASS_ALLOWED=True.
if [ "$WEBSPIDER_ENV" = "Dev" ]; then
    BUILD_ENV_DEV_BYPASS="True"
else
    BUILD_ENV_DEV_BYPASS="False"
fi
mkdir -p "$SOURCE_DIR/scripts/webspider/config"
cat > "$SOURCE_DIR/scripts/webspider/config/_build_env.py" << EOF
# SPDX-FileCopyrightText: 2026 WebSpider Studios
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by scripts/unix/build.sh - DO NOT EDIT
BUILD_ENVIRONMENT = "$WEBSPIDER_ENV"
DEV_BYPASS_ALLOWED = $BUILD_ENV_DEV_BYPASS
EOF

# Configure with CMake (all platform logic handled in settings.sh)
echo "Configuring WebSpider 3D build - Blender: $BLENDER_BUILD_ENV, WebSpider 3D Environment: $WEBSPIDER_ENV for $PLATFORM..."
cmake -C "$CMAKE_DIR/webspider_overrides.cmake" \
    $CMAKE_GENERATOR_ARGS \
    -S "$SOURCE_DIR" \
    -B "$BUILD_ENV_DIR" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Build (all platform-specific args handled in settings.sh)
echo "Building Blender in $BLENDER_BUILD_ENV mode for WebSpider 3D environment: $WEBSPIDER_ENV"
echo "Using $BUILD_CORES cores for parallel build"
cmake --build "$BUILD_ENV_DIR" $BUILD_ARGS
cmake --build "$BUILD_ENV_DIR" --target install --config "$BLENDER_BUILD_ENV"

# Generate runtime configuration for the bundle
echo "Generating runtime configuration for bundle..."
BUNDLE_CONFIG_DIR="$BUILD_ENV_DIR/bin/WebSpider3D.app/Contents/Resources/$BLENDER_VERSION/config"
python3 "$ROOT_DIR/scripts/generate_config.py" --output "$BUNDLE_CONFIG_DIR/webspider.json"

# Install Python packages using the generated Python binary
echo "Installing Python packages for WebSpider 3D..."

# Determine base path for embedded Python based on platform
if [ "$PLATFORM" = "macOS" ]; then
    EMBEDDED_PYTHON_BIN="$BUILD_ENV_DIR/bin/WebSpider3D.app/Contents/Resources/$BLENDER_VERSION/python/bin/python$PYTHON_VERSION"
    EMBEDDED_SITE_PACKAGES="$BUILD_ENV_DIR/bin/WebSpider3D.app/Contents/Resources/$BLENDER_VERSION/python/lib/python$PYTHON_VERSION/site-packages"
elif [ "$PLATFORM" = "Linux" ]; then
    EMBEDDED_PYTHON_BIN="$BUILD_ENV_DIR/bin/$BLENDER_VERSION/python/bin/python$PYTHON_VERSION"
    EMBEDDED_SITE_PACKAGES="$BUILD_ENV_DIR/bin/$BLENDER_VERSION/python/lib/python$PYTHON_VERSION/site-packages"
else
    echo "Error: Unsupported platform: $PLATFORM"
    exit 1
fi

PYTHON_BIN=""
for candidate in \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python${PYTHON_VERSION}" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python3" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python"; do
    if [[ -x "$candidate" ]]; then
        PYTHON_BIN="$candidate"
        break
    fi
done

SITE_PACKAGES="$PY_BASE/$BLENDER_VERSION/python/lib/python${PYTHON_VERSION}/site-packages"
REQUIREMENTS_FILE="$(dirname "$SCRIPT_DIR")/python_requirements.txt"

if [[ -n "$PYTHON_BIN" ]]; then
    echo "Found Python binary: $PYTHON_BIN"
    mkdir -p "$SITE_PACKAGES"
    
    # Check if requirements file exists
    if [[ -f "$REQUIREMENTS_FILE" ]]; then
        echo "Installing packages from: $REQUIREMENTS_FILE"
        
        # Force pip to install to the embedded Python's site-packages
        # Use --no-user to prevent installation to user site-packages
        # Use --target to specify the exact location
        if "$PYTHON_BIN" -m pip install --no-user --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
            echo "Successfully installed Python packages to embedded Python site-packages"
        elif command -v pip3 >/dev/null 2>&1; then
            echo "Embedded pip failed, trying system pip with --target..."
            if pip3 install --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
                echo "Successfully installed Python packages using system pip"
            else
                echo "Warning: Failed to install Python packages from requirements file"
            fi
        else
            echo "Warning: No pip available, skipping Python package installation"
        fi
    else
        echo "Warning: Requirements file not found at: $REQUIREMENTS_FILE"
        exit 1
    fi
else
    echo "Warning: Python binary not found under: $PY_BASE/$BLENDER_VERSION/python/bin"
fi

# Done
echo "=== Build Complete ==="
echo "Python packages installed from: $REQUIREMENTS_FILE"
echo "Run WebSpider 3D using: $BUILD_ENV_DIR/bin/WebSpider 3D.app/Contents/MacOS/WebSpider 3D"